server:
  port: 8080

spring:
  application:
    name: pr-api-gateway
  cloud:
    gateway:
      routes:
        - id: pr-precificando-back
          uri: lb://PR-PRECIFICANDO-BACK
          predicates:
            - Path=/pr-precificando-back/**

pr:
  serviceRegistry:
    username: serviceregistry
    password: vento123

eureka:
  client:
    service-url:
      defaultZone: 'http://${pr.serviceRegistry.username}:${pr.serviceRegistry.password}@localhost:8761/eureka'
    enabled: true
  instance:
    hostname: localhost