server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: precificando-back
          uri: lb://PRECIFICANDO-BACK
          predicates:
            - Path=/precificando-back/**

pr:
  serviceRegistry:
    username: serviceregistry
    password: vento123

eureka:
  client:
    service-url:
      defaultZone: 'http://${pr.serviceRegistry.username}:${pr.serviceRegistry.password}@localhost:8761/eureka'
    enabled: true
  instance:
    hostname: localhost